-- 테이블 삭제
DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CARTS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CATEGORY_MAPPING CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_ORDER_ITEMS;
DROP SEQUENCE SEQ_ORDERS;
DROP SEQUENCE SEQ_CARTS;
DROP SEQUENCE SEQ_PRODUCT_CATEGORY_MAPPING;
DROP SEQUENCE SEQ_PRODUCTS;
DROP SEQUENCE SEQ_CATEGORIES;
DROP SEQUENCE SEQ_USERS;

-- USERS(유저) 테이블
CREATE TABLE USERS (
    USER_NO         NUMBER PRIMARY KEY,
    USER_ID         VARCHAR2(15) NOT NULL,
    USER_NAME       VARCHAR2(50) NOT NULL,
    USER_PASSWORD   VARCHAR2(100) NOT NULL,
    USER_PHONE      VARCHAR2(20),
    USER_EMAIL      VARCHAR2(100) NOT NULL,
    USER_STATUS     VARCHAR2(20) NOT NULL,
    USER_ROLE       VARCHAR2(20) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE
);

-- PRODUCTS(상품) 테이블
CREATE TABLE PRODUCTS (
    PRODUCT_NO      NUMBER PRIMARY KEY,
    PRODUCT_ID      VARCHAR2(20) NOT NULL,
    PRODUCT_NAME    VARCHAR2(100) NOT NULL,
    PRODUCT_DESC    VARCHAR2(500),
    PRICE           NUMBER NOT NULL,
    STOCK_QTY       NUMBER DEFAULT 0,
    PRODUCT_STATUS  VARCHAR2(20) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE
);

-- CATEGORIES(카테고리) 테이블
CREATE TABLE CATEGORIES (
    CATEGORY_NO     NUMBER PRIMARY KEY,
    CATEGORY_ID     VARCHAR2(20) NOT NULL,
    PARENT_NO       NUMBER,
    CATEGORY_NAME   VARCHAR2(50) NOT NULL,
    SORT_ORDER      NUMBER DEFAULT 1
);

-- PRODUCT_CATEGORY_MAPPING(상품카테고리매핑) 테이블
CREATE TABLE PRODUCT_CATEGORY_MAPPING (
    MAPPING_NO      NUMBER PRIMARY KEY,
    PRODUCT_NO      NUMBER NOT NULL,
    CATEGORY_NO     NUMBER NOT NULL,
    SORT_ORDER      NUMBER DEFAULT 1
);

-- CARTS(장바구니) 테이블
CREATE TABLE CARTS (
    CART_NO         NUMBER PRIMARY KEY,
    USER_NO         NUMBER NOT NULL,
    PRODUCT_NO      NUMBER NOT NULL,
    QUANTITY        NUMBER NOT NULL
);

-- ORDERS(주문) 테이블
CREATE TABLE ORDERS (
    ORDER_NO        NUMBER PRIMARY KEY,
    USER_NO         NUMBER NOT NULL,
    ORDER_STATUS    VARCHAR2(20) NOT NULL,
    ORDER_DATE      DATE DEFAULT SYSDATE,
    TOTAL_PRICE     NUMBER NOT NULL
);

-- ORDER_ITEMS(주문상세) 테이블
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_NO       NUMBER PRIMARY KEY,
    ORDER_NO            NUMBER NOT NULL,
    PRODUCT_NO          NUMBER NOT NULL,
    ORDER_PRICE         NUMBER NOT NULL,
    QUANTITY            NUMBER NOT NULL,
    ITEM_TOTAL_PRICE    NUMBER NOT NULL
);

-- 시퀀스
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORIES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_CATEGORY_MAPPING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CARTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER_ITEMS START WITH 1 INCREMENT BY 1;

-- 관리자
INSERT INTO USERS VALUES (
    SEQ_USERS.NEXTVAL,
    'admin',
    '관리자',
    '1234',
    '010-0000-0000',
    'admin',
    '정상',
    '관리자',
    SYSDATE
);

-- 카테고리
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORIES.NEXTVAL, 'COMPUTER', NULL, '컴퓨터', 1);
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORIES.NEXTVAL, 'PERIPHERAL', NULL, '주변기기', 2);

INSERT INTO CATEGORIES VALUES (SEQ_CATEGORIES.NEXTVAL, 'LAPTOP', 1, '노트북', 1);
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORIES.NEXTVAL, 'DESKTOP', 1, '데스크탑', 2);
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORIES.NEXTVAL, 'KEYBOARD', 2, '키보드', 1);
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORIES.NEXTVAL, 'MOUSE', 2, '마우스', 2);

-- 상품
INSERT INTO PRODUCTS VALUES (
    SEQ_PRODUCTS.NEXTVAL,
    'P001',
    'LG 그램 노트북',
    '가벼운 노트북',
    1500000,
    10,
    '정상',
    SYSDATE
);

INSERT INTO PRODUCTS VALUES (
    SEQ_PRODUCTS.NEXTVAL,
    'P002',
    '삼성 데스크탑',
    '사무용 데스크탑',
    900000,
    5,
    '정상',
    SYSDATE
);

INSERT INTO PRODUCTS VALUES (
    SEQ_PRODUCTS.NEXTVAL,
    'P003',
    '기계식 키보드',
    '청축 키보드',
    120000,
    15,
    '정상',
    SYSDATE
);

INSERT INTO PRODUCTS VALUES (
    SEQ_PRODUCTS.NEXTVAL,
    'P004',
    '로지텍 마우스',
    '무선 마우스',
    30000,
    20,
    '정상',
    SYSDATE
);

-- 매핑
INSERT INTO PRODUCT_CATEGORY_MAPPING VALUES (SEQ_PRODUCT_CATEGORY_MAPPING.NEXTVAL, 1, 3, 1);
INSERT INTO PRODUCT_CATEGORY_MAPPING VALUES (SEQ_PRODUCT_CATEGORY_MAPPING.NEXTVAL, 2, 4, 1);
INSERT INTO PRODUCT_CATEGORY_MAPPING VALUES (SEQ_PRODUCT_CATEGORY_MAPPING.NEXTVAL, 3, 5, 1);
INSERT INTO PRODUCT_CATEGORY_MAPPING VALUES (SEQ_PRODUCT_CATEGORY_MAPPING.NEXTVAL, 4, 6, 1);
commit;

select *
from users;

SELECT CATEGORY_NO, CATEGORY_ID, PARENT_NO, CATEGORY_NAME, SORT_ORDER
FROM CATEGORIES;