-- =========================================================
-- 전체 객체 삭제
-- FK 참조 관계를 고려하여 자식 테이블부터 삭제
-- =========================================================

-- 인덱스 삭제
DROP INDEX IDX_COMMENTS_PARENT;
DROP INDEX IDX_COMMENTS_USER;
DROP INDEX IDX_COMMENTS_PRODUCT;
DROP INDEX IDX_ORDER_ITEMS_PRODUCT;
DROP INDEX IDX_ORDER_ITEMS_ORDER;
DROP INDEX IDX_ORDERS_STATUS;
DROP INDEX IDX_ORDERS_USER;
DROP INDEX IDX_CART_PRODUCT;
DROP INDEX IDX_CART_USER;
DROP INDEX IDX_PCM_CATEGORY;
DROP INDEX IDX_PCM_PRODUCT;
DROP INDEX IDX_PRODUCT_IMAGES_PRODUCT;
DROP INDEX IDX_PRODUCTS_STATUS;
DROP INDEX IDX_PRODUCTS_NAME;
DROP INDEX IDX_CATEGORIES_PARENT;

-- 테이블 삭제
DROP TABLE PRODUCT_COMMENTS CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CARTS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CATEGORY_MAPPING CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IMAGES CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_PRODUCT_COMMENTS;
DROP SEQUENCE SEQ_ORDER_ITEMS;
DROP SEQUENCE SEQ_ORDERS;
DROP SEQUENCE SEQ_CARTS;
DROP SEQUENCE SEQ_PRODUCT_CATEGORY_MAPPING;
DROP SEQUENCE SEQ_PRODUCT_IMAGES;
DROP SEQUENCE SEQ_PRODUCTS;
DROP SEQUENCE SEQ_CATEGORIES;
DROP SEQUENCE SEQ_USERS;