-- ---------------------------------------------------------
-- [INDEX] 조회 성능 개선을 위한 인덱스
-- ---------------------------------------------------------
CREATE INDEX IDX_CATEGORIES_PARENT ON CATEGORIES (PARENT_CATEGORY_NO);

CREATE INDEX IDX_PRODUCTS_NAME ON PRODUCTS (PRODUCT_NAME);
CREATE INDEX IDX_PRODUCTS_STATUS ON PRODUCTS (PRODUCT_STATUS);

CREATE INDEX IDX_PRODUCT_IMAGES_PRODUCT ON PRODUCT_IMAGES (PRODUCT_NO);

CREATE INDEX IDX_PCM_PRODUCT ON PRODUCT_CATEGORY_MAPPING (PRODUCT_NO);
CREATE INDEX IDX_PCM_CATEGORY ON PRODUCT_CATEGORY_MAPPING (CATEGORY_NO);

CREATE INDEX IDX_CART_USER ON CARTS (USER_NO);
CREATE INDEX IDX_CART_PRODUCT ON CARTS (PRODUCT_NO);

CREATE INDEX IDX_ORDERS_USER ON ORDERS (USER_NO);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS (ORDER_STATUS);

CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS (ORDER_NO);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT ON ORDER_ITEMS (PRODUCT_NO);

CREATE INDEX IDX_COMMENTS_PRODUCT ON PRODUCT_COMMENTS (PRODUCT_NO);
CREATE INDEX IDX_COMMENTS_USER ON PRODUCT_COMMENTS (USER_NO);
CREATE INDEX IDX_COMMENTS_PARENT ON PRODUCT_COMMENTS (PARENT_COMMENT_NO);